#pragma once

typedef enum {
    LINEARFORM_OPERATION_OK = 0,
    MEMORY_ALLOCATION_FAILED = 100,
    LINEARFORM_NOT_DEFINED = 200,
    OPERATION_NOT_DEFINED = 201,
    INCOMPATIBLE_LINEARFORM_TYPES = 300,
    DIMENSION_MISMATCH = 400
} LinearFormErrors;